version: "3"

services:
  app:
    image: drakona/node:14-alpine-auto
    volumes:
      - .:/srv
    ports:
      - "8000:80"
      - "8080:8080"
    tty: true
    working_dir: /srv
    command: make install run
